# Generated by Django 3.2 on 2021-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageCategory', models.CharField(choices=[('1', 'Category1'), ('2', 'Category2'), ('3', 'Category3'), ('4', 'Category4')], default='1', max_length=2)),
                ('imageContent', models.ImageField(default=None, upload_to='static/images')),
            ],
        ),
    ]
