# Generated by Django 3.2 on 2021-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='imageCategory',
            field=models.CharField(choices=[('Category1', 'Category1'), ('Category2', 'Category2'), ('Category3', 'Category3'), ('Category4', 'Category4')], default='1', max_length=20),
        ),
    ]
